server:
    port: 80
    
spring:
    application:
        name: mysj-center
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Mar.130118
        username: root
        url: jdbc:mysql://123.207.35.210:3306/center?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: true
    security:
        user:
            name: root
            password: root